### ISSUE TITLE
EnvRaw cuts off the REDIS_URL from the deployment

### ISSUE THREAD

**Issue by cakuros** [datawire/edge-stack#16]
## Summary

When using the `envRaw` value, it removes the default `REDIS_URL` environment variable, so it must be included in the actual `envRaw` string.  If you specify `envRaw` without setting `REDIS_URL`, Edge Stack will start without a redis configured, which will result in all of the problems associated with having a misconfigured redis (ratelimit and auth meters won't work, ACME won't work, DevPortal won't work, etc)

## Replicator

- Create a values.yaml file that uses envRaw:
```yaml
emissary-ingress:
  envRaw: |
    - name: AMBASSADOR_ENVOY_BASE_ID
     - name: AES_LOG_LEVEL
      value: "trace"
    - name: POLL_EVERY_SECS
      value: "60"
    - name: AMBASSADOR_ENVOY_BASE_ID
      value: "4"
    - name: AMBASSADOR_ENVOY_API_VERSION
      value: "V3"
    - name: AES_RATELIMIT_PREVIEW
      value: "true"
 ```

- Run `helm template -n ambassador edge-stack --devel datawire/edge-stack -f values.yaml`.

- Inspect the generated yaml to find the edge-stack deployment, no REDIS_URL env variable is present:
```yaml
...
      containers:
        - name: emissary-ingress
          image: docker.io/datawire/aes:2.0.1-ea
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
            - name: admin
              containerPort: 8877
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: AMBASSADOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AES_LOG_LEVEL
              value: "trace"
            - name: POLL_EVERY_SECS
              value: "60"
            - name: AMBASSADOR_ENVOY_BASE_ID
              value: "4"
            - name: AMBASSADOR_ENVOY_API_VERSION
              value: "V3"
            - name: AES_RATELIMIT_PREVIEW
              value: "true"

          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
...
```
