### ISSUE TITLE
Host - mapping associating not working.

### ISSUE THREAD

**Issue by pbabilas** [datawire/edge-stack#63]
Hi,
I've tried to make my configuration in edge-stack like here: 
https://www.getambassador.io/docs/edge-stack/latest/topics/running/host-crd/

But despite my label selector, all hosts gets all mappings.

mappings:

```
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  generation: 1
  labels:
    host-nb_outlet: nb_outlet
  name: isearch-wasiol
  namespace: test-edgestack
spec:
  ambassador_id:
  - --apiVersion-v3alpha1-only--default
  precedence: 2
  prefix: /wasiol
  rewrite: ""
  service: isearch.test-edgestack
  timeout_ms: 0
  hostname: a2d461472a026efc.ci.merce.cloud

---

apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  generation: 1
  labels:
    host-raccoon: raccoon
  name: iuploader-wasiol
  namespace: test-edgestack
spec:
  ambassador_id:
  - --apiVersion-v3alpha1-only--default
  precedence: 2
  prefix: /wasiol
  rewrite: ""
  service: iuploader.test-edgestack
  timeout_ms: 0
  hostname: a3e23aacf7a776c2.ci.merce.cloud
```

and host:
```
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: raccoon
  namespace: test-edgestack
spec:
  ambassador_id:
  - --apiVersion-v3alpha1-only--default
  hostname: a3e23aacf7a776c2.ci.merce.cloud
  requestPolicy:
    insecure:
      action: Route
      additionalPort: -1
  selector:
    matchLabels:
      host-raccoon: raccoon
---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: nb-outlet
  namespace: test-edgestack
spec:
  ambassador_id:
  - --apiVersion-v3alpha1-only--default
  hostname: a2d461472a026efc.ci.merce.cloud
  requestPolicy:
    insecure:
      action: Route
      additionalPort: -1
  selector:
    matchLabels:
      host-nb_outlet: nb_outlet
```

Here the mapping for one domains:
![foo](https://share.merce.com/files/jQEncIGOb7.png "diag")
![foo](https://share.merce.com/files/MFk1iGFPTg.png "diag")

Is there any misconfiguration been done? or it's just not working?
