### ISSUE TITLE
oauth2 filter disable mulitcookie

### ISSUE THREAD

**Issue by tzzcfrank** [datawire/edge-stack#81]
I used oauth2 filter and configured multiple domain names in protectedOrigins. When using one of the domain names for single sign-on, the mulitcookie will automatically redirect the request to another domain name. Can I turn this off? We do not need to share cookies.

**Comment by cakuros** [comment]
Ultimately I think this would mean that you need to create separate OAuth `Filters` for each domain.  When you have multiple domains under the protected origin, what you're effectively telling Edge Stack to do is to handle a single OAuth session across all domains listed in the protectedOrigins.  I.e., if you have example1.com and example2.com listed under protectedOrigins, then logging on to example1.com also logs you onto example2.com, so you could navigate to example2.com without needing to log on again.  You should basically think of each OAuth `Filter` as single RP's session.

If each domain is, instead, considered a separate OAuth session, then they should have different `Filters`, so instead of having a single OAuth `Filter` with both example1.com and example2.com in the same protectedOrigin, you would have 2 separate `Filters` with individual protectedOrigins, even if they're using the same credentials and trying to communicate with the same OP.

**Comment by cakuros** [comment]
A simple example might look something like the following:

```yaml
---
# Basic OAuth filter
apiVersion: getambassador.io/v3alpha1
kind: Filter
metadata:
  name: keycloak-filter-domain1
spec:
  OAuth2:
    authorizationURL: https://keycloak.example.com/auth/realms/my-realm
    audience: ambassador-labs
    clientID: ambassador-labs
    secret: <secret>
    protectedOrigins:
    - origin: https://ckuro1.example.com
    
---
# Basic OAuth filter
apiVersion: getambassador.io/v3alpha1
kind: Filter
metadata:
  name: keycloak-filter-domain2
spec:
  OAuth2:
    authorizationURL: https://keycloak.example.com/auth/realms/my-realm
    audience: ambassador-labs
    clientID: ambassador-labs
    secret: <secret>
    protectedOrigins:
    - origin: https://ckuro2.example.com

---
apiVersion: getambassador.io/v3alpha1
kind: FilterPolicy
metadata:
  name: filter-policy
spec:
  rules:
    - host: "ckuro1.example.com"
      path: "*"
      filters:
        - name: keycloak-filter-domain1
    - host: "ckuro2.example.com"
      path: "*"
      filters:
        - name: keycloak-filter-domain2
```
